export default [
    {
        "login": "preethamb97",
        "id": 31663960,
        "node_id": "MDQ6VXNlcjMxNjYzOTYw",
        "avatar_url": "https://avatars.githubusercontent.com/u/31663960?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/preethamb97",
        "html_url": "https://github.com/preethamb97",
        "followers_url": "https://api.github.com/users/preethamb97/followers",
        "following_url": "https://api.github.com/users/preethamb97/following{/other_user}",
        "gists_url": "https://api.github.com/users/preethamb97/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/preethamb97/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/preethamb97/subscriptions",
        "organizations_url": "https://api.github.com/users/preethamb97/orgs",
        "repos_url": "https://api.github.com/users/preethamb97/repos",
        "events_url": "https://api.github.com/users/preethamb97/events{/privacy}",
        "received_events_url": "https://api.github.com/users/preethamb97/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "jdcollahuazo1",
        "id": 56968086,
        "node_id": "MDQ6VXNlcjU2OTY4MDg2",
        "avatar_url": "https://avatars.githubusercontent.com/u/56968086?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jdcollahuazo1",
        "html_url": "https://github.com/jdcollahuazo1",
        "followers_url": "https://api.github.com/users/jdcollahuazo1/followers",
        "following_url": "https://api.github.com/users/jdcollahuazo1/following{/other_user}",
        "gists_url": "https://api.github.com/users/jdcollahuazo1/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jdcollahuazo1/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jdcollahuazo1/subscriptions",
        "organizations_url": "https://api.github.com/users/jdcollahuazo1/orgs",
        "repos_url": "https://api.github.com/users/jdcollahuazo1/repos",
        "events_url": "https://api.github.com/users/jdcollahuazo1/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jdcollahuazo1/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "omar990408",
        "id": 56983106,
        "node_id": "MDQ6VXNlcjU2OTgzMTA2",
        "avatar_url": "https://avatars.githubusercontent.com/u/56983106?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/omar990408",
        "html_url": "https://github.com/omar990408",
        "followers_url": "https://api.github.com/users/omar990408/followers",
        "following_url": "https://api.github.com/users/omar990408/following{/other_user}",
        "gists_url": "https://api.github.com/users/omar990408/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/omar990408/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/omar990408/subscriptions",
        "organizations_url": "https://api.github.com/users/omar990408/orgs",
        "repos_url": "https://api.github.com/users/omar990408/repos",
        "events_url": "https://api.github.com/users/omar990408/events{/privacy}",
        "received_events_url": "https://api.github.com/users/omar990408/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "MosFazli",
        "id": 69136464,
        "node_id": "MDQ6VXNlcjY5MTM2NDY0",
        "avatar_url": "https://avatars.githubusercontent.com/u/69136464?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/MosFazli",
        "html_url": "https://github.com/MosFazli",
        "followers_url": "https://api.github.com/users/MosFazli/followers",
        "following_url": "https://api.github.com/users/MosFazli/following{/other_user}",
        "gists_url": "https://api.github.com/users/MosFazli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/MosFazli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/MosFazli/subscriptions",
        "organizations_url": "https://api.github.com/users/MosFazli/orgs",
        "repos_url": "https://api.github.com/users/MosFazli/repos",
        "events_url": "https://api.github.com/users/MosFazli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/MosFazli/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "AkshatRastogi-1nC0re",
        "id": 71638737,
        "node_id": "MDQ6VXNlcjcxNjM4NzM3",
        "avatar_url": "https://avatars.githubusercontent.com/u/71638737?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/AkshatRastogi-1nC0re",
        "html_url": "https://github.com/AkshatRastogi-1nC0re",
        "followers_url": "https://api.github.com/users/AkshatRastogi-1nC0re/followers",
        "following_url": "https://api.github.com/users/AkshatRastogi-1nC0re/following{/other_user}",
        "gists_url": "https://api.github.com/users/AkshatRastogi-1nC0re/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/AkshatRastogi-1nC0re/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/AkshatRastogi-1nC0re/subscriptions",
        "organizations_url": "https://api.github.com/users/AkshatRastogi-1nC0re/orgs",
        "repos_url": "https://api.github.com/users/AkshatRastogi-1nC0re/repos",
        "events_url": "https://api.github.com/users/AkshatRastogi-1nC0re/events{/privacy}",
        "received_events_url": "https://api.github.com/users/AkshatRastogi-1nC0re/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "savith12321",
        "id": 73011842,
        "node_id": "MDQ6VXNlcjczMDExODQy",
        "avatar_url": "https://avatars.githubusercontent.com/u/73011842?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/savith12321",
        "html_url": "https://github.com/savith12321",
        "followers_url": "https://api.github.com/users/savith12321/followers",
        "following_url": "https://api.github.com/users/savith12321/following{/other_user}",
        "gists_url": "https://api.github.com/users/savith12321/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/savith12321/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/savith12321/subscriptions",
        "organizations_url": "https://api.github.com/users/savith12321/orgs",
        "repos_url": "https://api.github.com/users/savith12321/repos",
        "events_url": "https://api.github.com/users/savith12321/events{/privacy}",
        "received_events_url": "https://api.github.com/users/savith12321/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "blackstorm0514",
        "id": 74522790,
        "node_id": "MDQ6VXNlcjc0NTIyNzkw",
        "avatar_url": "https://avatars.githubusercontent.com/u/74522790?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/blackstorm0514",
        "html_url": "https://github.com/blackstorm0514",
        "followers_url": "https://api.github.com/users/blackstorm0514/followers",
        "following_url": "https://api.github.com/users/blackstorm0514/following{/other_user}",
        "gists_url": "https://api.github.com/users/blackstorm0514/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/blackstorm0514/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/blackstorm0514/subscriptions",
        "organizations_url": "https://api.github.com/users/blackstorm0514/orgs",
        "repos_url": "https://api.github.com/users/blackstorm0514/repos",
        "events_url": "https://api.github.com/users/blackstorm0514/events{/privacy}",
        "received_events_url": "https://api.github.com/users/blackstorm0514/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "TopCodeBeast",
        "id": 93806749,
        "node_id": "U_kgDOBZdgnQ",
        "avatar_url": "https://avatars.githubusercontent.com/u/93806749?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/TopCodeBeast",
        "html_url": "https://github.com/TopCodeBeast",
        "followers_url": "https://api.github.com/users/TopCodeBeast/followers",
        "following_url": "https://api.github.com/users/TopCodeBeast/following{/other_user}",
        "gists_url": "https://api.github.com/users/TopCodeBeast/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/TopCodeBeast/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/TopCodeBeast/subscriptions",
        "organizations_url": "https://api.github.com/users/TopCodeBeast/orgs",
        "repos_url": "https://api.github.com/users/TopCodeBeast/repos",
        "events_url": "https://api.github.com/users/TopCodeBeast/events{/privacy}",
        "received_events_url": "https://api.github.com/users/TopCodeBeast/received_events",
        "type": "User",
        "site_admin": false
    }
]
