export default {
        "login": "aenoboa1",
        "id": 56968012,
        "node_id": "MDQ6VXNlcjU2OTY4MDEy",
        "avatar_url": "https://avatars.githubusercontent.com/u/56968012?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/aenoboa1",
        "html_url": "https://github.com/aenoboa1",
        "followers_url": "https://api.github.com/users/aenoboa1/followers",
        "following_url": "https://api.github.com/users/aenoboa1/following{/other_user}",
        "gists_url": "https://api.github.com/users/aenoboa1/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/aenoboa1/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/aenoboa1/subscriptions",
        "organizations_url": "https://api.github.com/users/aenoboa1/orgs",
        "repos_url": "https://api.github.com/users/aenoboa1/repos",
        "events_url": "https://api.github.com/users/aenoboa1/events{/privacy}",
        "received_events_url": "https://api.github.com/users/aenoboa1/received_events",
        "type": "User",
        "site_admin": false,
        "name": "Andres Noboa V.",
        "company": null,
        "blog": "",
        "location": "Planet Earth",
        "email": null,
        "hireable": null,
        "bio": "Attention is all you need ",
        "twitter_username": null,
        "public_repos": 21,
        "public_gists": 3,
        "followers": 8,
        "following": 68,
        "created_at": "2019-10-24T14:02:49Z",
        "updated_at": "2022-09-21T00:48:36Z"
}
